[package]
name = "nodejscomrust"
version = "0.1.1"
authors = ["Neviim <neviimdev@gmail.com>"]
edition = "2018"

[lib]
name = "hello_lib"
path = "src/lib.rs"
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = "0.2.59"